import './colorsTypes-style.scss';
import './colors/colors-style.scss';
import './colors/darkShade100/darkShade100%-style.scss'
import './colors/darkShade75/darkShade75%-style.scss'
import './colors/darkShade50/darkShade50%-style.scss'
import './colors/darkShade25/darkShade25%-style.scss'
import './colors/darkShade5/darkShade5%-style.scss'
import './colors/purple/purple-style.scss'
import './colors/green/green-style.scss'
import './types/types-style.scss'
import './types/h1/h1-style.scss'
import './types/h2/h2-style.scss'
import './types/h3/h3-style.scss'
import './types/body/body-style.scss'